##### Labeler ##########################################################################################################
# Enable "labeler" for your PR that would add labels to PRs based on the paths that are modified in the PR.
labelPRBasedOnFilePath:

  # Add 'base code' label to any change within the 'internal' folder or any subfolders
  base code:
    - 'internal/**/*'

  # Add 'CI' to any file changes within '.github' folder or any subfolders
  CI:
    - '.github/**/*'
    - 'staticcheck.conf'
    - '.sonarcloud.properties'

  # Add 'config' label to any change within the 'configs' and 'deployments' folders and any change to Kconfig, go.mod
  config:
    - 'configs/**/*'
    - 'Kconfig'
    - 'deployments/**/*'
    - 'go.mod'

  # Add 'documentation' to any changes within 'docs' and 'api' folders or any subfolders and any change to *.md files
  documentation:
    - '**/*.md'
    - 'docs/**/*'
    - 'api/**/*'

  # Add 'examples' label to any change within the 'examples' and 'test' folders or any subfolders
  examples:
    - 'examples/**/*'
    - 'test/**/*'

  # Add 'mqtt' label to any change within the 'mqtt' folder or any subfolders
  mqtt:
    - 'internal/common/mqtt/**/*'

  # Add 'security' label to any change within the 'securemgr' folder or any subfolders and 'SECURITY.md' file
  security:
    - 'internal/controller/securemgr/**/*'
    - '.github/SECURITY.md'

  # Add 'tc' label to any change within the 'internal' folder or any subfolders  related to test coverage
  tc:
    - 'internal/**/*_test.go'
    - 'internal/**/mocks_*.go'

  # Add 'tools' label to any change within the 'tools' and 'script' folders or any subfolders
  tools:
    - 'tools/**/*'
    - 'script/**/*'

  # Add 'VersionTag' label to any change VERSION file
  VersionTag:
    - 'VERSION'

  # Add 'Web UI' label to any change within the 'web' and `webui`folders or any subfolders
  Web UI:
    - 'web/**/*'
    - 'internal/webui/**/*'

##### Greetings ########################################################################################################
# Comment to be posted to welcome users when they open their first PR
firstPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines.

# Comment to be posted to congratulate user on their first merged PR
firstPRMergeComment: >
  Awesome work, congrats on your first merged pull request!

# Comment to be posted to on first time issues
firstIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template!
