version: 2
updates:
# Enable version updates for gomod
  - package-ecosystem: "gomod"
    # Look for `gomod` in the `root` directory
    directory: "/"
    # Check for updates once a month
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*docker*"
      - dependency-name: "*edgexfoundry*"
      - dependency-name: "mock"
    # Allow up to 15 open pull requests for gomod dependencies
    open-pull-requests-limit: 15

# Enable version updates for Actions
  - package-ecosystem: "github-actions"
    # Look for `.github/workflows` in the `root` directory
    directory: "/"
    # Check for updates once a month
    schedule:
      interval: "monthly"
    # Allow up to 15 open pull requests for github-actions dependencies
    open-pull-requests-limit: 15
