version: 2
updates:
# Enable version updates for gomod
  - package-ecosystem: "gomod"
    # Look for `gomod` in the `root` directory
    directory: "/"
    # Check for updates once a month
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*docker*"

# Enable version updates for Actions
  - package-ecosystem: "github-actions"
    # Look for `.github/workflows` in the `root` directory
    directory: "/"
    # Check for updates once a month
    schedule:
      interval: "monthly"
