/*******************************************************************************
 * Copyright 2020 Samsung Electronics All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *******************************************************************************/

// Code generated by MockGen. DO NOT EDIT.
// Source: common/networkhelper (interfaces: Network)

// Package mocks is a generated GoMock package.
package mocks

import (
	net "net"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNetwork is a mock of Network interface.
type MockNetwork struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkMockRecorder
}

// MockNetworkMockRecorder is the mock recorder for MockNetwork.
type MockNetworkMockRecorder struct {
	mock *MockNetwork
}

// NewMockNetwork creates a new mock instance.
func NewMockNetwork(ctrl *gomock.Controller) *MockNetwork {
	mock := &MockNetwork{ctrl: ctrl}
	mock.recorder = &MockNetworkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetwork) EXPECT() *MockNetworkMockRecorder {
	return m.recorder
}

// AppendSubscriber mocks base method.
func (m *MockNetwork) AppendSubscriber() chan []net.IP {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendSubscriber")
	ret0, _ := ret[0].(chan []net.IP)
	return ret0
}

// AppendSubscriber indicates an expected call of AppendSubscriber.
func (mr *MockNetworkMockRecorder) AppendSubscriber() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendSubscriber", reflect.TypeOf((*MockNetwork)(nil).AppendSubscriber))
}

// CheckConnectivity mocks base method.
func (m *MockNetwork) CheckConnectivity() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckConnectivity")
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckConnectivity indicates an expected call of CheckConnectivity.
func (mr *MockNetworkMockRecorder) CheckConnectivity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckConnectivity", reflect.TypeOf((*MockNetwork)(nil).CheckConnectivity))
}

// GetIPs mocks base method.
func (m *MockNetwork) GetIPs() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIPs")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIPs indicates an expected call of GetIPs.
func (mr *MockNetworkMockRecorder) GetIPs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIPs", reflect.TypeOf((*MockNetwork)(nil).GetIPs))
}

// GetMACAddress mocks base method.
func (m *MockNetwork) GetMACAddress() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMACAddress")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMACAddress indicates an expected call of GetMACAddress.
func (mr *MockNetworkMockRecorder) GetMACAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMACAddress", reflect.TypeOf((*MockNetwork)(nil).GetMACAddress))
}

// GetNetInterface mocks base method.
func (m *MockNetwork) GetNetInterface() ([]net.Interface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNetInterface")
	ret0, _ := ret[0].([]net.Interface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetInterface indicates an expected call of GetNetInterface.
func (mr *MockNetworkMockRecorder) GetNetInterface() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetInterface", reflect.TypeOf((*MockNetwork)(nil).GetNetInterface))
}

// GetOutboundIP mocks base method.
func (m *MockNetwork) GetOutboundIP() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutboundIP")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOutboundIP indicates an expected call of GetOutboundIP.
func (mr *MockNetworkMockRecorder) GetOutboundIP() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutboundIP", reflect.TypeOf((*MockNetwork)(nil).GetOutboundIP))
}

// GetVirtualIP mocks base method.
func (m *MockNetwork) GetVirtualIP() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVirtualIP")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVirtualIP indicates an expected call of GetVirtualIP.
func (mr *MockNetworkMockRecorder) GetVirtualIP() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVirtualIP", reflect.TypeOf((*MockNetwork)(nil).GetVirtualIP))
}

// StartNetwork mocks base method.
func (m *MockNetwork) StartNetwork() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartNetwork")
}

// StartNetwork indicates an expected call of StartNetwork.
func (mr *MockNetworkMockRecorder) StartNetwork() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartNetwork", reflect.TypeOf((*MockNetwork)(nil).StartNetwork))
}
