// Code generated by MockGen. DO NOT EDIT.
// Source: cipher.go

// Package mock_cipher is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	cipher "restinterface/cipher"
)

// MockIEdgeCipherer is a mock of IEdgeCipherer interface
type MockIEdgeCipherer struct {
	ctrl     *gomock.Controller
	recorder *MockIEdgeCiphererMockRecorder
}

// MockIEdgeCiphererMockRecorder is the mock recorder for MockIEdgeCipherer
type MockIEdgeCiphererMockRecorder struct {
	mock *MockIEdgeCipherer
}

// NewMockIEdgeCipherer creates a new mock instance
func NewMockIEdgeCipherer(ctrl *gomock.Controller) *MockIEdgeCipherer {
	mock := &MockIEdgeCipherer{ctrl: ctrl}
	mock.recorder = &MockIEdgeCiphererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIEdgeCipherer) EXPECT() *MockIEdgeCiphererMockRecorder {
	return m.recorder
}

// EncryptByte mocks base method
func (m *MockIEdgeCipherer) EncryptByte(byteData []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptByte", byteData)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptByte indicates an expected call of EncryptByte
func (mr *MockIEdgeCiphererMockRecorder) EncryptByte(byteData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptByte", reflect.TypeOf((*MockIEdgeCipherer)(nil).EncryptByte), byteData)
}

// EncrptJSONToByte mocks base method
func (m *MockIEdgeCipherer) EncryptJSONToByte(jsonMap map[string]interface{}) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptJSONToByte", jsonMap)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncrptJSONToByte indicates an expected call of EncrptJSONToByte
func (mr *MockIEdgeCiphererMockRecorder) EncryptJSONToByte(jsonMap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptJSONToByte", reflect.TypeOf((*MockIEdgeCipherer)(nil).EncryptJSONToByte), jsonMap)
}

// DecryptByte mocks base method
func (m *MockIEdgeCipherer) DecryptByte(byteData []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptByte", byteData)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptByte indicates an expected call of DecryptByte
func (mr *MockIEdgeCiphererMockRecorder) DecryptByte(byteData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptByte", reflect.TypeOf((*MockIEdgeCipherer)(nil).DecryptByte), byteData)
}

// DecryptByteToJSON mocks base method
func (m *MockIEdgeCipherer) DecryptByteToJSON(data []byte) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptByteToJSON", data)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptByteToJSON indicates an expected call of DecryptByteToJSON
func (mr *MockIEdgeCiphererMockRecorder) DecryptByteToJSON(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptByteToJSON", reflect.TypeOf((*MockIEdgeCipherer)(nil).DecryptByteToJSON), data)
}

// MockCipherSetter is a mock of CipherSetter interface
type MockCipherSetter struct {
	ctrl     *gomock.Controller
	recorder *MockCipherSetterMockRecorder
}

// MockCipherSetterMockRecorder is the mock recorder for MockCipherSetter
type MockCipherSetterMockRecorder struct {
	mock *MockCipherSetter
}

// NewMockCipherSetter creates a new mock instance
func NewMockCipherSetter(ctrl *gomock.Controller) *MockCipherSetter {
	mock := &MockCipherSetter{ctrl: ctrl}
	mock.recorder = &MockCipherSetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCipherSetter) EXPECT() *MockCipherSetterMockRecorder {
	return m.recorder
}

// SetCipher mocks base method
func (m *MockCipherSetter) SetCipher(cipher cipher.IEdgeCipherer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCipher", cipher)
}

// SetCipher indicates an expected call of SetCipher
func (mr *MockCipherSetterMockRecorder) SetCipher(cipher interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCipher", reflect.TypeOf((*MockCipherSetter)(nil).SetCipher), cipher)
}
