/*******************************************************************************
* Copyright 2021 Samsung Electronics All Rights Reserved.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*
*******************************************************************************/

// Code generated by MockGen. DO NOT EDIT.
// Source: cloudsync.go

package mocks

import (
	gomock "github.com/golang/mock/gomock"
	mqttmgr "github.com/lf-edge/edge-home-orchestration-go/internal/common/mqtt"
	reflect "reflect"
)

// MockCloudSync is a mock of CloudSync interface
type MockCloudSync struct {
	ctrl     *gomock.Controller
	recorder *MockCloudSyncMockRecorder
}

// MockCloudSyncMockRecorder is the mock recorder for MockCloudSync
type MockCloudSyncMockRecorder struct {
	mock *MockCloudSync
}

// NewMockCloudSync creates a new mock instance
func NewMockCloudSync(ctrl *gomock.Controller) *MockCloudSync {
	mock := &MockCloudSync{ctrl: ctrl}
	mock.recorder = &MockCloudSyncMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockCloudSync) EXPECT() *MockCloudSyncMockRecorder {
	return _m.recorder
}

// InitiateCloudSync mocks base method
func (_m *MockCloudSync) InitiateCloudSync(isCloudSet string) error {
	ret := _m.ctrl.Call(_m, "InitiateCloudSync", isCloudSet)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitiateCloudSync indicates an expected call of StartCloudSync
func (_mr *MockCloudSyncMockRecorder) InitiateCloudSync(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "InitiateCloudSync", reflect.TypeOf((*MockCloudSync)(nil).InitiateCloudSync), arg0)
}

// RequestPublish mocks base method
func (_m *MockCloudSync) RequestPublish(host string, clientID string, message mqttmgr.Message, topic string) string {
	ret := _m.ctrl.Call(_m, "RequestPublish", host)
	ret0, _ := ret[0].(string)
	return ret0
}

// RequestPublish indicates an expected call of RequestPublish
func (_mr *MockCloudSyncMockRecorder) RequestPublish(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "RequestPublish", reflect.TypeOf((*MockCloudSync)(nil).RequestPublish), arg0)
}

// RequestSubscribe mocks base method
func (_m *MockCloudSync) RequestSubscribe(host string, clientID string, topic string) string {
	ret := _m.ctrl.Call(_m, "RequestSubscribe", host)
	ret0, _ := ret[0].(string)
	return ret0
}

// RequestSubscribe indicates an expected call of RequestSubscribe
func (_mr *MockCloudSyncMockRecorder) RequestSubscribe(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "RequestSubscribe", reflect.TypeOf((*MockCloudSync)(nil).RequestSubscribe), arg0)
}
