// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mock_client is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	cipher "restinterface/cipher"
	client "restinterface/client"
)

// MockClientApi is a mock of Clienter interface
type MockClientApi struct {
	ctrl     *gomock.Controller
	recorder *MockClientApiMockRecorder
}

// MockClientApiMockRecorder is the mock recorder for MockClientApi
type MockClientApiMockRecorder struct {
	mock *MockClientApi
}

// NewMockClientApi creates a new mock instance
func NewMockClientApi(ctrl *gomock.Controller) *MockClientApi {
	mock := &MockClientApi{ctrl: ctrl}
	mock.recorder = &MockClientApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClientApi) EXPECT() *MockClientApiMockRecorder {
	return m.recorder
}

// SetCipher mocks base method
func (m *MockClientApi) SetCipher(cipher cipher.IEdgeCipherer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCipher", cipher)
}

// SetCipher indicates an expected call of SetCipher
func (mr *MockClientApiMockRecorder) SetCipher(cipher interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCipher", reflect.TypeOf((*MockClientApi)(nil).SetCipher), cipher)
}

// DoExecuteRemoteDevice mocks base method
func (m *MockClientApi) DoExecuteRemoteDevice(appInfo map[string]interface{}, target string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoExecuteRemoteDevice", appInfo, target)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoExecuteRemoteDevice indicates an expected call of DoExecuteRemoteDevice
func (mr *MockClientApiMockRecorder) DoExecuteRemoteDevice(appInfo, target interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoExecuteRemoteDevice", reflect.TypeOf((*MockClientApi)(nil).DoExecuteRemoteDevice), appInfo, target)
}

// DoNotifyAppStatusRemoteDevice mocks base method
func (m *MockClientApi) DoNotifyAppStatusRemoteDevice(statusNotificationInfo map[string]interface{}, appID uint64, target string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoNotifyAppStatusRemoteDevice", statusNotificationInfo, appID, target)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoNotifyAppStatusRemoteDevice indicates an expected call of DoNotifyAppStatusRemoteDevice
func (mr *MockClientApiMockRecorder) DoNotifyAppStatusRemoteDevice(statusNotificationInfo, appID, target interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoNotifyAppStatusRemoteDevice", reflect.TypeOf((*MockClientApi)(nil).DoNotifyAppStatusRemoteDevice), statusNotificationInfo, appID, target)
}

// DoGetScoreRemoteDevice mocks base method
func (m *MockClientApi) DoGetScoreRemoteDevice(appName, target string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoGetScoreRemoteDevice", appName, target)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoGetScoreRemoteDevice indicates an expected call of DoGetScoreRemoteDevice
func (mr *MockClientApiMockRecorder) DoGetScoreRemoteDevice(appName, target interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoGetScoreRemoteDevice", reflect.TypeOf((*MockClientApi)(nil).DoGetScoreRemoteDevice), appName, target)
}

// MockClientSetter is a mock of Setter interface
type MockClientSetter struct {
	ctrl     *gomock.Controller
	recorder *MockClientSetterMockRecorder
}

// MockClientSetterMockRecorder is the mock recorder for MockClientSetter
type MockClientSetterMockRecorder struct {
	mock *MockClientSetter
}

// NewMockClientSetter creates a new mock instance
func NewMockClientSetter(ctrl *gomock.Controller) *MockClientSetter {
	mock := &MockClientSetter{ctrl: ctrl}
	mock.recorder = &MockClientSetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClientSetter) EXPECT() *MockClientSetterMockRecorder {
	return m.recorder
}

// SetClient mocks base method
func (m *MockClientSetter) SetClient(clientAPI client.Clienter) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetClient", clientAPI)
}

// SetClient indicates an expected call of SetClient
func (mr *MockClientSetterMockRecorder) SetClient(clientAPI interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetClient", reflect.TypeOf((*MockClientSetter)(nil).SetClient), clientAPI)
}
