name: "datastorage"
manufacturer: "Home Edge"
model: "Home Edge"
labels:
 - "rest"
 - "json"
 - "numeric"
 - "float"
 - "int"
description: "REST Device"

deviceResources:
  - name: json
    description: "JSON message"
    properties:
      value:
        { type: "String", readWrite: "RW" , mediaType : "application/json" }
      units:
        { type: "String", readWrite: "R" }
  - name: int
    description: "Int64 value"
    properties:
      value:
        { type: "Int64", readWrite: "RW" , mediaType : "text/plain" }
      units:
        { type: "String", readWrite: "R"}
  - name: float
    description: "Float64 value"
    properties:
      value:
        { type: "Float64", readWrite: "RW" , mediaType : "text/plain" }
      units:
        { type: "String", readWrite: "R" }
  - name: jpeg
    description: "Jpeg image"
    properties:
      value:
        { type: "Binary", readWrite: "RW" , mediaType : "image/jpeg" }
      units:
        { type: "String", readWrite: "R" }
  - name: png
    description: "png image"
    properties:
      value:
        { type: "Binary", readWrite: "RW" , mediaType : "image/png" }
      units:
        { type: "String", readWrite: "R" }
  - name: string
    description: "String"
    properties:
      value:
        { type: "String", readWrite: "RW" , mediaType : "text/plain"}
      units:
        { type: "String", readWrite: "R" }
