swagger: '2.0'
info:
  title: Edge Orchestration API
  description: >-
    
    This provides functionality to execute a service on a remote edge device. 
    
    
    Requirement)
    
    1. Two or more Edge Orchestration devices.
    
    2. Each devices should be connected at same WIFI network.   
    
  version: v1-20190611
schemes:
  - http
tags:
  - name: Service Execution
    description: Execute a Service on the other Device based on Score
paths:
  '/api/v1/orchestration/services':
    post:
      tags:
        - Service Execution
      description: Execute a Service on the other Device
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      - in: "body"
        name: "body"
        description: "Name is Service Category, declared in config file and it determines which scoring method will be applied.
        
        
        Args is a list of Shell Command to execute Service."
        
        required: true
        schema:
          $ref: "#/definitions/service"
      responses:
        '200':
          description: Successful operation, return handle, as a client ID    
          schema:     
            $ref: "#/definitions/handle"   
definitions:
  service:
    required:
      - ServiceName
      - ServiceInfo
    properties:
      ServiceName:
        type: string
        example: container_service
      ServiceInfo:
        type: array
        example:
          - {"ExecutionType":"native", "ExecCmd":["hellow-world"]}
          - {"ExecutionType":"container", "ExecCmd":["docker", "run", "hello-world"]}
          - {"ExecutionType":"android", "ExecCmd":["com.example.hello-world"]}
      StatusCallbackURI:
        type: string
        example: "http://192.168.10.151:9090/example/notification"

  handle:
    required:
      - Handle
    properties:
      Handle:
        type: integer
        format: int32
        example: 7
