---
name: Lint and Vet Analysis
on: [push, pull_request]

jobs:
  lintvetanalysis:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: '1.15.6'

      - name: Set env vars (golint)
        run: |
          go get golang.org/x/lint/golint
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Lint Analysis
        run: |
          golint ./internal/...

      - name: Vet Analysis
        run: |
          go vet -v ./internal/...

